### ISSUE TITLE
(Question)

### ISSUE THREAD

**Issue by TsinJu** [mchestr/displex#280]
Is there a docker image to pull? 
I can't really figure out from the documentation how to install the bot, but I would like to use it

**Comment by mchestr** [comment]
Yes I publish to ghcr, currently running it on my k8s cluster, but documentation for setup is lacking.

Check out the manifests here https://github.com/mchestr/home-cluster/tree/main/kubernetes%2Fapps%2Fdefault%2Fdisplex
